version: "3.3"

services:
  database:
    container_name: database
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./vols/init.sql:/docker-entrypoint-initdb.d/init.sql

